<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    public function run()
    {
        // Admin
        User::updateOrCreate(
            ['email' => 'admin@gmail.com'],
            [
                'name' => 'Admin Miftah',
                'password' => Hash::make('admin123'),
                'role' => 'admin',
                'email_verified_at' => now(),
                'is_active' => true,
                'telepon' => '081234567000',
                'jenis_kelamin' => 'L',
                'alamat' => 'Cimahi, Jawa Barat',
            ]
        );

        // 5 Pembina
        $pembinas = [
            [
                'name' => 'Budi Santoso, S.Pd',
                'email' => 'budisantoso@gmail.com',
                'password' => bcrypt('pembina123'),
                'role' => 'pembina',
                'telepon' => '081234567001',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Raya Cimahi No. 10, Cimahi',
                'email_verified_at' => now(),
                'is_active' => true,
            ],
            [
                'name' => 'Siti Nurhaliza, S.Sn',
                'email' => 'sitinurhaliza@gmail.com',
                'password' => bcrypt('pembina123'),
                'role' => 'pembina',
                'telepon' => '081234567002',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Sudirman No. 25, Cimahi',
                'email_verified_at' => now(),
                'is_active' => true,
            ],
            [
                'name' => 'Ahmad Rifai, M.Pd',
                'email' => 'ahmadrifai@gmail.com',
                'password' => bcrypt('pembina123'),
                'role' => 'pembina',
                'telepon' => '081234567003',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Gatot Subroto No. 15, Cimahi',
                'email_verified_at' => now(),
                'is_active' => true,
            ],
            [
                'name' => 'Dr. Fatimah Zahra, M.Ed',
                'email' => 'fatimahzahra@gmail.com',
                'password' => bcrypt('pembina123'),
                'role' => 'pembina',
                'telepon' => '081234567004',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Veteran No. 8, Cimahi',
                'email_verified_at' => now(),
                'is_active' => true,
            ],
            [
                'name' => 'Muhammad Yusuf, S.Kom',
                'email' => 'muhammadyusuf@gmail.com',
                'password' => bcrypt('pembina123'),
                'role' => 'pembina',
                'telepon' => '081234567005',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Diponegoro No. 12, Cimahi',
                'email_verified_at' => now(),
                'is_active' => true,
            ],
        ];

        foreach ($pembinas as $pembina) {
            User::updateOrCreate(['email' => $pembina['email']], $pembina);
        }

        // 20 Siswa
        $siswas = [
            [
                'name' => 'Ahmad Rizki Pratama',
                'email' => 'ahmadrizkipratama@gmail.com',
                'nis' => '2024001',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 85.5,
                'minat' => json_encode(['olahraga', 'teknologi']),
                'tanggal_lahir' => '2007-03-15',
                'alamat' => 'Jl. Mawar No. 10, Cimahi',
                'telepon' => '081234560001',
                'prestasi' => 'Juara 1 Olimpiade Matematika Tingkat Sekolah 2023',
            ],
            [
                'name' => 'Fatimah Azzahra Putri',
                'email' => 'fatimahaazzahraputri@gmail.com',
                'nis' => '2024002',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 88.2,
                'minat' => json_encode(['seni', 'akademik']),
                'tanggal_lahir' => '2007-07-22',
                'alamat' => 'Jl. Melati No. 15, Cimahi',
                'telepon' => '081234560002',
                'prestasi' => 'Juara 2 Lomba Lukis Tingkat Kota 2023',
            ],
            [
                'name' => 'Dimas Ardiansyah',
                'email' => 'dimasardiansyah@gmail.com',
                'nis' => '2024003',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 82.0,
                'minat' => json_encode(['olahraga', 'kepemimpinan']),
                'tanggal_lahir' => '2007-01-10',
                'alamat' => 'Jl. Dahlia No. 8, Cimahi',
                'telepon' => '081234560003',
                'prestasi' => 'Ketua OSIS SMP 2022-2023',
            ],
            [
                'name' => 'Nur Aini Rahmawati',
                'email' => 'nurainirahmaati@gmail.com',
                'nis' => '2024004',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 90.1,
                'minat' => json_encode(['akademik', 'seni']),
                'tanggal_lahir' => '2007-05-18',
                'alamat' => 'Jl. Anggrek No. 20, Cimahi',
                'telepon' => '081234560004',
                'prestasi' => 'Juara 1 Debat Bahasa Indonesia Tingkat Provinsi 2023',
            ],
            [
                'name' => 'Rizky Maulana',
                'email' => 'rizkymaulana@gmail.com',
                'nis' => '2024005',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 79.5,
                'minat' => json_encode(['teknologi', 'musik']),
                'tanggal_lahir' => '2007-11-03',
                'alamat' => 'Jl. Kenanga No. 5, Cimahi',
                'telepon' => '081234560005',
                'prestasi' => 'Juara 3 Lomba Band Tingkat Sekolah 2023',
            ],
            [
                'name' => 'Sari Dewi Lestari',
                'email' => 'saridewilestari@gmail.com',
                'nis' => '2024006',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 87.3,
                'minat' => json_encode(['seni', 'budaya']),
                'tanggal_lahir' => '2007-09-12',
                'alamat' => 'Jl. Cempaka No. 12, Cimahi',
                'telepon' => '081234560006',
                'prestasi' => 'Juara 1 Tari Tradisional Tingkat Kabupaten 2023',
            ],
            [
                'name' => 'Rahman Hakim',
                'email' => 'rahmanhakim@gmail.com',
                'nis' => '2024007',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 84.7,
                'minat' => json_encode(['akademik', 'bahasa']),
                'tanggal_lahir' => '2007-06-25',
                'alamat' => 'Jl. Flamboyan No. 7, Cimahi',
                'telepon' => '081234560007',
                'prestasi' => 'Juara 2 English Speech Contest 2023',
            ],
            [
                'name' => 'Anisa Putri Maharani',
                'email' => 'anisaputrimaharani@gmail.com',
                'nis' => '2024008',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 91.2,
                'minat' => json_encode(['akademik', 'kepemimpinan']),
                'tanggal_lahir' => '2007-04-08',
                'alamat' => 'Jl. Bougenville No. 18, Cimahi',
                'telepon' => '081234560008',
                'prestasi' => 'Juara 1 Olimpiade Fisika Tingkat Kota 2023',
            ],
            [
                'name' => 'Bayu Kusuma Wardana',
                'email' => 'bayukusumawardana@gmail.com',
                'nis' => '2024009',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 78.9,
                'minat' => json_encode(['olahraga', 'musik']),
                'tanggal_lahir' => '2007-11-30',
                'alamat' => 'Jl. Kamboja No. 22, Cimahi',
                'telepon' => '081234560009',
                'prestasi' => 'Juara 2 Futsal Antar Sekolah 2023',
            ],
            [
                'name' => 'Dewi Sartika Ningrum',
                'email' => 'dewisartikaningrum@gmail.com',
                'nis' => '2024010',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 86.5,
                'minat' => json_encode(['seni', 'media']),
                'tanggal_lahir' => '2007-02-14',
                'alamat' => 'Jl. Teratai No. 14, Cimahi',
                'telepon' => '081234560010',
                'prestasi' => 'Juara 1 Fotografi Tingkat Sekolah 2023',
            ],
            [
                'name' => 'Fajar Ramadhan',
                'email' => 'fajarramadhan@gmail.com',
                'nis' => '2024011',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 83.4,
                'minat' => json_encode(['teknologi', 'akademik']),
                'tanggal_lahir' => '2007-08-17',
                'alamat' => 'Jl. Sakura No. 9, Cimahi',
                'telepon' => '081234560011',
                'prestasi' => 'Juara 3 Lomba Programming 2023',
            ],
            [
                'name' => 'Indah Permatasari',
                'email' => 'indahpermatasari@gmail.com',
                'nis' => '2024012',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 89.7,
                'minat' => json_encode(['seni', 'bahasa']),
                'tanggal_lahir' => '2007-12-05',
                'alamat' => 'Jl. Lily No. 16, Cimahi',
                'telepon' => '081234560012',
                'prestasi' => 'Juara 1 Puisi Tingkat Provinsi 2023',
            ],
            [
                'name' => 'Galang Prasetyo',
                'email' => 'galangprasetyo@gmail.com',
                'nis' => '2024013',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 81.8,
                'minat' => json_encode(['olahraga', 'kepemimpinan']),
                'tanggal_lahir' => '2007-10-28',
                'alamat' => 'Jl. Iris No. 11, Cimahi',
                'telepon' => '081234560013',
                'prestasi' => 'Kapten Tim Basket Sekolah 2023',
            ],
            [
                'name' => 'Hana Safitri',
                'email' => 'hanasafitri@gmail.com',
                'nis' => '2024014',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 85.9,
                'minat' => json_encode(['akademik', 'budaya']),
                'tanggal_lahir' => '2007-01-22',
                'alamat' => 'Jl. Tulip No. 19, Cimahi',
                'telepon' => '081234560014',
                'prestasi' => 'Juara 2 Cerdas Cermat Sejarah 2023',
            ],
            [
                'name' => 'Irfan Maulana',
                'email' => 'irfanmaulana@gmail.com',
                'nis' => '2024015',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 80.3,
                'minat' => json_encode(['teknologi', 'seni']),
                'tanggal_lahir' => '2007-09-07',
                'alamat' => 'Jl. Violet No. 6, Cimahi',
                'telepon' => '081234560015',
                'prestasi' => 'Juara 2 Desain Grafis Tingkat Kota 2023',
            ],
            [
                'name' => 'Jasmine Aulia',
                'email' => 'jasmineaulia@gmail.com',
                'nis' => '2024016',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 88.6,
                'minat' => json_encode(['bahasa', 'media']),
                'tanggal_lahir' => '2007-04-15',
                'alamat' => 'Jl. Matahari No. 21, Cimahi',
                'telepon' => '081234560016',
                'prestasi' => 'Juara 1 Jurnalistik Tingkat Sekolah 2023',
            ],
            [
                'name' => 'Kevin Pratama',
                'email' => 'kevinpratama@gmail.com',
                'nis' => '2024017',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 82.7,
                'minat' => json_encode(['olahraga', 'teknologi']),
                'tanggal_lahir' => '2007-07-11',
                'alamat' => 'Jl. Cemara No. 13, Cimahi',
                'telepon' => '081234560017',
                'prestasi' => 'Juara 1 Badminton Tingkat Sekolah 2023',
            ],
            [
                'name' => 'Laila Maharani',
                'email' => 'lailamaharani@gmail.com',
                'nis' => '2024018',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 87.1,
                'minat' => json_encode(['seni', 'kepemimpinan']),
                'tanggal_lahir' => '2007-03-29',
                'alamat' => 'Jl. Bunga Raya No. 17, Cimahi',
                'telepon' => '081234560018',
                'prestasi' => 'Ketua Ekstrakurikuler Tari 2023',
            ],
            [
                'name' => 'Muhammad Fadli',
                'email' => 'muhammadfadli@gmail.com',
                'nis' => '2024019',
                'jenis_kelamin' => 'L',
                'nilai_rata_rata' => 84.2,
                'minat' => json_encode(['akademik', 'teknologi']),
                'tanggal_lahir' => '2007-06-08',
                'alamat' => 'Jl. Pinus No. 4, Cimahi',
                'telepon' => '081234560019',
                'prestasi' => 'Juara 2 Robotika Tingkat Kota 2023',
            ],
            [
                'name' => 'Nabila Azahra',
                'email' => 'nabilaazahra@gmail.com',
                'nis' => '2024020',
                'jenis_kelamin' => 'P',
                'nilai_rata_rata' => 86.8,
                'minat' => json_encode(['bahasa', 'budaya']),
                'tanggal_lahir' => '2007-05-26',
                'alamat' => 'Jl. Orchid No. 23, Cimahi',
                'telepon' => '081234560020',
                'prestasi' => 'Juara 1 Storytelling Bahasa Inggris 2023',
            ],
        ];

        foreach ($siswas as $siswa) {
            User::updateOrCreate(
                ['email' => $siswa['email']],
                array_merge($siswa, [
                    'password' => Hash::make('siswa123'),
                    'role' => 'siswa',
                    'email_verified_at' => now(),
                    'is_active' => true,
                ])
            );
        }

        $this->command->info('Users seeded successfully!');
        $this->command->info('Admin: admin@gmail.com / admin123');
        $this->command->info('Pembina: budisantoso@gmail.com / pembina123');
        $this->command->info('Siswa: ahmadrizkipratama@gmail.com / siswa123');
    }
}
